### ISSUE TITLE
Transfer vscode-bazel to bazel-contrib

### ISSUE THREAD

**Issue by meteorcloudy** [bazel-contrib/vscode-bazel#412]
**Description:**

This issue proposes transferring the vscode-bazel repository from the `bazelbuild` GitHub organization to the `bazel-contrib` GitHub organization, which is owned by the [Community for Bazel](https://github.com/bazel-contrib/.github/blob/master/Community%20for%20Bazel%20Technical%20Charter.pdf) project under the Linux Foundation.

**GitHub Discussion:** https://github.com/orgs/bazelbuild/discussions/2

**Impacts:**

* GitHub issues & PRs will be transferred to the new repository.
* Branch protection rules will need to be transferred to the new repository.
* Individual maintainers will be transferred to the new repository.
* GitHub teams will NOT be transferred to the new repository and will need to be re-created.
* Bazel CI configurations will need to be updated to point to the new repository.

Read more on [Transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) from GitHub documentation.

**Checklist:**

* [x] Obtain approval from the current project maintainers (@fweikert, @jfirebaugh, @cameron-martin).
* [x] Obtain approval from the bazel-contrib SIG (@alexeagle).
* [ ] Initiate the transfer process on GitHub (@meteorcloudy).
<del> * [ ] Update Bazel CI settings and confirm presubmit & postsubmit work (@meteorcloudy). <del/>

**Comment by alexeagle** [comment]
Notes from SIG meeting: this transfer was unanimously approved by a thumbs-up vote.

**Comment by vogelsgesang** [comment]
> Obtain approval from the current project maintainers (@fweikert, @jfirebaugh, @cameron-martin).

Approved

After transferring the repository itself, we should probably also figure out what we want to do about the ownership of the MarketPlace extension

**Comment by meteorcloudy** [comment]
@fweikert I think we discussed this before, could we transfer the extension to a different account?

**Comment by vogelsgesang** [comment]
Yep there was some discussion around this previously in Slack [in this thread](https://bazelbuild.slack.com/archives/CA31HN1T3/p1713864887926349?thread_ts=1713561498.904219&cid=CA31HN1T3)

**Comment by meteorcloudy** [comment]
Cool, then I guess we can continue to help publishing the extension for now. I'll do the transfer now

**Comment by meteorcloudy** [comment]
Done, please check CI/CD works correctly.
